apiVersion: v1
kind: Service
metadata:
  name: vault-go-demo-oauth
spec:
  selector:
    app: vault-go-demo-oauth
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: 9090
      targetPort: 9090
  # externalTrafficPolicy: Cluster

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-go-demo-oauth
spec:
  ingressClassName: nginx
  rules:
    # - host: ab422299ee4.........-671924557.us-east-1.elb.amazonaws.com
    - host: dev.andrewlklaas.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vault-go-demo-oauth
                port:
                  number: 9090
          # - path: "/*"
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: vault-go-demo-oauth
          #       port:
          #         number: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-go-demo-oauth
  labels:
    app: vault-go-demo-oauth
    version: v1
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: vault-go-demo-oauth
      version: v1
  template:
    metadata: 
      name: vault-go-demo-oauth
      labels:
        app: vault-go-demo-oauth
        version: v1
    spec:
      serviceAccountName: vault-auth
      automountServiceAccountToken: true
      containers:
        - name: vault-go-demo-oauth
          image: aklaas2/vault-go-demo-oauth:latest
          ports:
          - containerPort: 9090
            name: http
            protocol: TCP
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "SYS_TIME"]